# Default trading configuration
# Numeric values may be customized.

default_cash: 100.0
# default stop loss percentage from purchase price (e.g., 0.05 = 5%)
default_stop_loss: 0.05
# list of additional tickers to fetch stats for in daily_results
extra_tickers:
  - "^RUT"
  - "IWO"
  - "XBI"

# Optional notification settings
# Set an email address or webhook URL to receive trade alerts
email: ""
webhook_url: ""
run_time: "09:00"

